### ISSUE TITLE
What does `location` column means?

### ISSUE THREAD

**Issue by DamarisDeng** [PascaDiMagliano-Lab/Gift-of-Life-Public-Repository#1]
Hi! I was reading the sample_info.csv (https://github.com/PascaDiMagliano-Lab/Gift-of-Life-Public-Repository/blob/master/data/samples_info.csv) in your data folder, and I was curious about what does `location` mean? Thank you in advance for your reply!

**Comment by aelhossiny** [comment]
Hi, thank you for your question. The location column indicates the position of the pancreas from the sample was acquired (pancreas head, pancreas tail, unknown)

**Comment by DamarisDeng** [comment]
Thanks for your reply! Got it!

From: Ahmed Elhossiny ***@***.***>
Date: Tuesday, July 4, 2023 at 20:12
To: PascaDiMagliano-Lab/Gift-of-Life-Public-Repository ***@***.***>
Cc: Junyang Deng ***@***.***>, Author ***@***.***>
Subject: Re: [PascaDiMagliano-Lab/Gift-of-Life-Public-Repository] What does `location` column means? (Issue #1)

Hi, thank you for your question. The location column indicates the position of the pancreas from the sample was acquired (pancreas head, pancreas tail, unknown)
